import {
  EventMetadata,
  Participant,
  Announcement,
  FeedbackItem,
  AgendaSession,
  MatchProfile,
  PublicEventCategory,
  CommunicationTone,
  UserAccount
} from './types';

export const CATEGORY_METADATA: Record<
  PublicEventCategory,
  {
    badgeClass: string;
    borderClass: string;
    bgClass: string;
    defaultTone: CommunicationTone;
    sampleTiers: string[];
    description: string;
  }
> = {
  'Civic & Government': {
    badgeClass: 'text-blue-400 bg-blue-500/10 border-blue-500/20',
    borderClass: 'border-blue-500/40',
    bgClass: 'bg-blue-950/20',
    defaultTone: 'Civic & Official',
    sampleTiers: ['Citizen Delegate', 'Elected Official', 'Observer', 'Press'],
    description: 'Town halls, municipal council meetings, civic forums & public policy hearings',
  },
  'Health & Wellness': {
    badgeClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
    borderClass: 'border-emerald-500/40',
    bgClass: 'bg-emerald-950/20',
    defaultTone: 'Warm & Community-First',
    sampleTiers: ['General Attendee', 'Healthcare Practitioner', 'Wellness Instructor', 'Volunteer'],
    description: 'Community health screenings, mindfulness retreats, fitness seminars & blood drives',
  },
  'Education & Career': {
    badgeClass: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
    borderClass: 'border-amber-500/40',
    bgClass: 'bg-amber-950/20',
    defaultTone: 'Educational & Informative',
    sampleTiers: ['Job Seeker', 'Recruiter / Employer', 'Speaker / Educator', 'Student Delegate'],
    description: 'Career expos, university summits, vocational workshops & mentorship fairs',
  },
  'Cultural & Festival': {
    badgeClass: 'text-purple-400 bg-purple-500/10 border-purple-500/20',
    borderClass: 'border-purple-500/40',
    bgClass: 'bg-purple-950/20',
    defaultTone: 'Celebratory & Festive',
    sampleTiers: ['General Guest', 'Performer / Artist', 'Artisan Vendor', 'VIP Guest'],
    description: 'Folk dances, international food galas, regional carnivals & ethnic celebrations',
  },
  'Sports & Fitness': {
    badgeClass: 'text-orange-400 bg-orange-500/10 border-orange-500/20',
    borderClass: 'border-orange-500/40',
    bgClass: 'bg-orange-950/20',
    defaultTone: 'High-Energy & Inspiring',
    sampleTiers: ['Athlete / Runner', 'Coach', 'Spectator', 'Medical Support'],
    description: 'Charity 5K runs, community athletic tournaments, youth leagues & fitness games',
  },
  'Community & Social Service': {
    badgeClass: 'text-rose-400 bg-rose-500/10 border-rose-500/20',
    borderClass: 'border-rose-500/40',
    bgClass: 'bg-rose-950/20',
    defaultTone: 'Warm & Community-First',
    sampleTiers: ['Volunteer', 'Community Organizer', 'Beneficiary Supporter', 'Partner NGO'],
    description: 'Food bank drives, neighborhood cleanups, environmental restoration & shelter aid',
  },
  'Business & Startup': {
    badgeClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/20',
    borderClass: 'border-indigo-500/40',
    bgClass: 'bg-indigo-950/20',
    defaultTone: 'Civic & Official',
    sampleTiers: ['Founder / Startup', 'Investor', 'Corporate Partner', 'General Delegate'],
    description: 'Pitch showcases, commerce expos, business mixers & entrepreneurship panels',
  },
  'Science & Tech Outreach': {
    badgeClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/20',
    borderClass: 'border-cyan-500/40',
    bgClass: 'bg-cyan-950/20',
    defaultTone: 'Educational & Informative',
    sampleTiers: ['Science Enthusiast', 'Researcher / Educator', 'Student Innovator', 'Presenter'],
    description: 'Public astronomy nights, STEM youth workshops, robotics showcases & lab open houses',
  },
  'Religious & Heritage': {
    badgeClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/20',
    borderClass: 'border-yellow-500/40',
    bgClass: 'bg-yellow-950/20',
    defaultTone: 'Reverent & Heritage-Focused',
    sampleTiers: ['Congregant / Pilgrim', 'Faith Leader', 'Heritage Historian', 'Volunteer Host'],
    description: 'Interfaith harmony assemblies, sacred ceremonies, heritage preservation walks & festivals',
  },
  'Entertainment': {
    badgeClass: 'text-pink-400 bg-pink-500/10 border-pink-500/20',
    borderClass: 'border-pink-500/40',
    bgClass: 'bg-pink-950/20',
    defaultTone: 'Celebratory & Festive',
    sampleTiers: ['Concert Goer', 'VIP Backstage', 'Featured Artist', 'Media / Press'],
    description: 'Live acoustic music nights, open-air theatre, comedy galas & indie film screenings',
  },
};

export const SEED_HOST_ACCOUNT: UserAccount = {
  id: 'host-demo-1',
  name: 'Eleanor Vance',
  email: 'eleanor.vance@cityevents.org',
  password: 'password123',
  role: 'host',
  profileCompleted: true,
  hostProfile: {
    fullName: 'Eleanor Vance',
    organization: 'Metropolitan Civic & Cultural Board',
    hostType: 'Government',
    designation: 'Director of Public Programs',
    officialEmail: 'eleanor.vance@cityevents.org',
    phone: '4155552671',
    city: 'San Francisco',
    state: 'CA',
    bio: 'Directing transparent civic assemblies, community health fairs, youth initiatives, and cultural heritage celebrations across the bay area.',
    website: 'https://cityevents.org',
    isAuthorized: true,
  },
};

export const SEED_PARTICIPANT_ACCOUNT: UserAccount = {
  id: 'part-demo-1',
  name: 'Marcus Chen',
  email: 'marcus.chen@community.org',
  password: 'password123',
  role: 'participant',
  company: 'Urban Health & Transit League',
  ticketTier: 'Delegate',
  avatarSeed: 'MC',
  registeredEventIds: ['evt-civic-1'],
};

export const SEED_EVENTS: EventMetadata[] = [
  {
    id: 'evt-civic-1',
    hostId: 'host-demo-1',
    title: 'Metro Civic Town Hall: Urban Sustainability & Public Transit 2026',
    category: 'Civic & Government',
    startDateTime: '2026-10-18T18:00',
    endDateTime: '2026-10-18T21:00',
    venue: 'City Council Assembly Chamber',
    city: 'San Francisco',
    state: 'CA',
    capacity: 250,
    description: 'A transparent civic forum bringing together municipal planning directors, ward representatives, and residents to review transit expansion and green corridors.',
    tone: 'Civic & Official',
    organizerName: 'Metropolitan Civic & Cultural Board',
    organizerContact: 'eleanor.vance@cityevents.org',
    entryType: 'Free Public Entry',
    status: 'Live',
    createdAt: '2026-10-01T08:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'evt-health-1',
    hostId: 'host-demo-1',
    title: 'PureMind Community Wellness & Holistic Health Expo 2026',
    category: 'Health & Wellness',
    startDateTime: '2026-10-22T08:30',
    endDateTime: '2026-10-22T16:00',
    venue: 'Riverfront Green Pavilion & Lawn',
    city: 'San Francisco',
    state: 'CA',
    capacity: 350,
    description: 'A rejuvenating public wellness festival offering free biometric health screenings, certified yoga clinics, sound baths, and accessible mental health support circles.',
    tone: 'Warm & Community-First',
    organizerName: 'Metropolitan Civic & Cultural Board',
    organizerContact: 'eleanor.vance@cityevents.org',
    entryType: 'Free Public Entry',
    status: 'Published',
    createdAt: '2026-09-28T10:00:00.000Z',
    updatedAt: '2026-09-30T14:30:00.000Z',
  },
  {
    id: 'evt-cultural-1',
    hostId: 'host-demo-1',
    title: 'Heritage Harmony: Global Folk & Culinary Festival 2026',
    category: 'Cultural & Festival',
    startDateTime: '2026-10-28T11:00',
    endDateTime: '2026-10-28T19:30',
    venue: 'Downtown Cultural Plaza & Amphitheater',
    city: 'San Francisco',
    state: 'CA',
    capacity: 600,
    description: 'An open cultural carnival celebrating ethnic music, traditional dance troupes, indigenous artisan crafts, and global culinary tastings from over 25 communities.',
    tone: 'Celebratory & Festive',
    organizerName: 'Metropolitan Civic & Cultural Board',
    organizerContact: 'eleanor.vance@cityevents.org',
    entryType: 'Free Public Entry',
    status: 'Published',
    createdAt: '2026-09-25T11:00:00.000Z',
    updatedAt: '2026-09-29T16:00:00.000Z',
  },
  {
    id: 'evt-sports-1',
    hostId: 'host-demo-1',
    title: 'Apex City 10K Charity Marathon & Fitness Games',
    category: 'Sports & Fitness',
    startDateTime: '2026-11-08T07:00',
    endDateTime: '2026-11-08T13:00',
    venue: 'Olympic Park & Lakeshore Running Circuit',
    city: 'San Francisco',
    state: 'CA',
    capacity: 500,
    description: 'An energizing community marathon and obstacle course raising funds for youth athletics equipment and accessible community sports fields.',
    tone: 'High-Energy & Inspiring',
    organizerName: 'Metropolitan Civic & Cultural Board',
    organizerContact: 'eleanor.vance@cityevents.org',
    entryType: 'Registration Required',
    status: 'Draft',
    createdAt: '2026-10-01T09:00:00.000Z',
    updatedAt: '2026-10-01T09:00:00.000Z',
  },
  {
    id: 'evt-entertainment-1',
    hostId: 'host-demo-1',
    title: 'EchoWaves Sunset Music & Performing Arts Gala 2026',
    category: 'Entertainment',
    startDateTime: '2026-09-15T18:00',
    endDateTime: '2026-09-15T22:30',
    venue: 'Marina Harbor Amphitheatre',
    city: 'San Francisco',
    state: 'CA',
    capacity: 450,
    description: 'An open-air evening celebrating local indie songwriters, acoustic ensembles, improv theatre, and community food stalls.',
    tone: 'Celebratory & Festive',
    organizerName: 'Metropolitan Civic & Cultural Board',
    organizerContact: 'eleanor.vance@cityevents.org',
    entryType: 'Ticketed RSVP',
    status: 'Completed',
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-09-16T10:00:00.000Z',
  },
];

export const SEED_PARTICIPANTS: Participant[] = [
  // For evt-civic-1
  {
    id: 'p-c1',
    eventId: 'evt-civic-1',
    name: 'Carlos Mendez',
    email: 'carlos.m@metrotransitcoalition.org',
    ticketTier: 'Delegate',
    isCheckedIn: true,
    company: 'Transit Advocates Coalition',
    role: 'Community Organizer',
    avatarSeed: 'CM',
    checkInTimestamp: '05:40 PM',
  },
  {
    id: 'p-c2',
    eventId: 'evt-civic-1',
    name: 'Hon. Diane Foster',
    email: 'd.foster@cityhall.gov',
    ticketTier: 'Speaker',
    isCheckedIn: true,
    company: 'City Council District 4',
    role: 'Council Member',
    avatarSeed: 'DF',
    checkInTimestamp: '05:45 PM',
  },
  {
    id: 'p-c3',
    eventId: 'evt-civic-1',
    name: 'Marcus Chen',
    email: 'marcus.chen@community.org',
    ticketTier: 'Delegate',
    isCheckedIn: false,
    company: 'Urban Health & Transit League',
    role: 'Delegate',
    avatarSeed: 'MC',
  },
  {
    id: 'p-c4',
    eventId: 'evt-civic-1',
    name: 'Aisha Al-Mansoor',
    email: 'aisha.m@urbanstudies.edu',
    ticketTier: 'General',
    isCheckedIn: false,
    company: 'Urban Policy League',
    role: 'Policy Researcher',
    avatarSeed: 'AA',
  },

  // For evt-health-1
  {
    id: 'p-h1',
    eventId: 'evt-health-1',
    name: 'Sara Lindqvist',
    email: 'sara.l@wellnessco.org',
    ticketTier: 'General',
    isCheckedIn: false,
    company: 'Community Member',
    role: 'Wellness Advocate',
    avatarSeed: 'SL',
  },
  {
    id: 'p-h2',
    eventId: 'evt-health-1',
    name: 'Dr. Julian Morales',
    email: 'j.morales@clinicallife.org',
    ticketTier: 'Speaker',
    isCheckedIn: false,
    company: 'Regional Health Clinic',
    role: 'Clinical Nutritionist',
    avatarSeed: 'JM',
  },

  // For evt-cultural-1
  {
    id: 'p-cl1',
    eventId: 'evt-cultural-1',
    name: 'Mateo Rossi',
    email: 'mateo.rossi@artscouncil.org',
    ticketTier: 'Performer',
    isCheckedIn: false,
    company: 'Rossi Folk Ensemble',
    role: 'Bandleader',
    avatarSeed: 'MR',
  },
  {
    id: 'p-cl2',
    eventId: 'evt-cultural-1',
    name: 'Sunita Sharma',
    email: 'sunita@heritagekitchen.org',
    ticketTier: 'Exhibitor',
    isCheckedIn: false,
    company: 'Spice Route Kitchen',
    role: 'Master Chef',
    avatarSeed: 'SS',
  },

  // For evt-entertainment-1 (completed event)
  {
    id: 'p-e1',
    eventId: 'evt-entertainment-1',
    name: 'Olivia Wilde',
    email: 'olivia@soundstage.fm',
    ticketTier: 'VIP',
    isCheckedIn: true,
    company: 'Acoustic Bay',
    role: 'Producer',
    avatarSeed: 'OW',
    checkInTimestamp: '06:10 PM',
  },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'a-c0',
    eventId: 'evt-civic-1',
    eventTitle: 'Metro Civic Town Hall: Urban Sustainability & Public Transit 2026',
    eventCategory: 'Civic & Government',
    title: 'Urgent: Main Auditorium Doors Open Early',
    message: 'Due to high expected civic attendance and security checkpoints at the North Gate, the City Council Assembly Chamber doors will open 30 minutes early at 5:30 PM. Please have your digital fastpass ready.',
    rawText: 'Doors open early at 5:30 due to high crowd.',
    polishedText: 'Due to high expected civic attendance and security checkpoints at the North Gate, the City Council Assembly Chamber doors will open 30 minutes early at 5:30 PM. Please have your digital fastpass ready.',
    type: 'Urgent',
    tone: 'Civic & Official',
    timestamp: '05:15 PM',
    targetAudience: 'All Attendees',
    isPinned: true,
    organizerName: 'Metropolitan Civic & Cultural Board',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    isDelivered: true,
    readBy: [],
  },
  {
    id: 'a-c1',
    eventId: 'evt-civic-1',
    eventTitle: 'Metro Civic Town Hall: Urban Sustainability & Public Transit 2026',
    eventCategory: 'Civic & Government',
    title: 'Row 3 Reserved for Public Testimony',
    message: 'Delegates registered for the open public testimony period are kindly requested to take their seats in Row 3 for smooth proceedings during the question round.',
    rawText: 'Speakers with question slips please assemble in Row 3 for the microphone.',
    polishedText: 'Delegates registered for the open public testimony period are kindly requested to take their seats in Row 3 for smooth proceedings during the question round.',
    type: 'Reminder',
    tone: 'Civic & Official',
    timestamp: '05:50 PM',
    targetAudience: 'All Attendees',
    isPinned: false,
    organizerName: 'Metropolitan Civic & Cultural Board',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
    isDelivered: true,
    readBy: [],
  },
  {
    id: 'a-h1',
    eventId: 'evt-health-1',
    eventTitle: 'PureMind Community Wellness & Holistic Health Expo 2026',
    eventCategory: 'Health & Wellness',
    title: 'Biometric Screenings Open at Health Station 1',
    message: 'Complimentary biometric wellness screenings and blood pressure tests will open promptly at Health Station 1. All registered visitors are warmly welcome!',
    rawText: 'Free blood pressure testing starts at 9am in Tent 1.',
    polishedText: 'Complimentary biometric wellness screenings and blood pressure tests will open promptly at Health Station 1. All visitors are warmly welcome!',
    type: 'General',
    tone: 'Warm & Community-First',
    timestamp: '08:30 AM',
    targetAudience: 'All Attendees',
    isPinned: false,
    organizerName: 'Metropolitan Civic & Cultural Board',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    isDelivered: true,
    readBy: [],
  },
  {
    id: 'a-h2',
    eventId: 'evt-health-1',
    eventTitle: 'PureMind Community Wellness & Holistic Health Expo 2026',
    eventCategory: 'Health & Wellness',
    title: 'Schedule Change: Sunset Sound Bath Moved to Lawn Stage',
    message: 'The Sunset Sound Bath and Breathwork workshop has been relocated from Pavilion B to the open-air Lawn Stage to accommodate more participants.',
    rawText: 'Sound bath moved to lawn stage.',
    polishedText: 'The Sunset Sound Bath and Breathwork workshop has been relocated from Pavilion B to the open-air Lawn Stage to accommodate more participants.',
    type: 'Schedule change',
    tone: 'Warm & Community-First',
    timestamp: '11:00 AM',
    targetAudience: 'All Attendees',
    isPinned: false,
    organizerName: 'Metropolitan Civic & Cultural Board',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
    isDelivered: true,
    readBy: [],
  },
];

export const SEED_FEEDBACKS: FeedbackItem[] = [
  {
    id: 'f-c1',
    eventId: 'evt-civic-1',
    authorName: 'Carlos Mendez',
    ticketTier: 'Delegate',
    ratings: { contentQuality: 5, logisticsVenue: 4, overallVibe: 5 },
    comment: 'Very orderly and transparent presentation. The live agenda mapping on Eventora is clear.',
    sentiment: 'Positive',
    sentimentScore: 0.92,
    aiSummary: 'Praised transparency and digital schedule tracking.',
    timestamp: '06:15 PM',
  },
];

export const SEED_AGENDA: AgendaSession[] = [
  // For evt-civic-1
  {
    id: 'c1',
    eventId: 'evt-civic-1',
    title: 'Call to Order & Public Transit Plan Briefing',
    timeSlot: '06:00 PM - 06:45 PM',
    room: 'Assembly Hall',
    speaker: 'Council President Sarah Jenkins',
    speakerRole: 'District 4 Representative',
    category: 'Deliberation',
    isBookmarked: true,
    isLive: true,
  },
  {
    id: 'c2',
    eventId: 'evt-civic-1',
    title: 'Open Microphone: Resident Questions & Ward Feedback',
    timeSlot: '06:45 PM - 08:00 PM',
    room: 'Assembly Hall',
    speaker: 'Citizen Panel & Planning Board',
    speakerRole: 'Open Public Floor',
    category: 'Public Forum',
    isBookmarked: false,
  },
  {
    id: 'c3',
    eventId: 'evt-civic-1',
    title: 'Closing Remarks & Next Steps on Civic Ordinances',
    timeSlot: '08:00 PM - 08:30 PM',
    room: 'Assembly Hall',
    speaker: 'Mayor Raymond Chen',
    speakerRole: 'Office of the Mayor',
    category: 'Resolution',
    isBookmarked: false,
  },

  // For evt-health-1
  {
    id: 'h1',
    eventId: 'evt-health-1',
    title: 'Morning Breathwork & Gentle Vinyasa Alignment',
    timeSlot: '08:30 AM - 09:30 AM',
    room: 'Lawn Pavilion East',
    speaker: 'Maya Lin',
    speakerRole: 'Holistic Yoga Master',
    category: 'Movement',
    isBookmarked: true,
    isLive: false,
  },
  {
    id: 'h2',
    eventId: 'evt-health-1',
    title: 'Nutrition on a Budget: Plant-Based Whole Foods Workshop',
    timeSlot: '10:00 AM - 11:15 AM',
    room: 'Workshop Tent B',
    speaker: 'Dr. Julian Morales',
    speakerRole: 'Clinical Nutritionist',
    category: 'Nutrition',
    isBookmarked: false,
  },
];

export const SEED_MATCHES: MatchProfile[] = [
  {
    id: 'm-c1',
    eventId: 'evt-civic-1',
    name: 'Aisha Al-Mansoor',
    role: 'Policy Researcher',
    company: 'Urban Policy League',
    matchScore: 94,
    aiPitch: 'Both interested in civic bicycle infrastructure and carbon reduction policy.',
    sharedInterests: ['Public Transit', 'Zoning Law', 'Clean Air'],
    location: 'Row 4, Seat 12',
  },
];
